export const recommend = [
    {
        image: "https://chinese.sarawaktourism.com/wp-content/uploads/2018/04/Village-in-the-clouds-sights-and-sounds-4-jungle-trekking-waterfall-bidayuh-landscape-600x400.jpg",
        name: "Villages above the clouds",
        shopName: "Kuching ",
        price: "240",
        discountedPrice: "200",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        soldNum: 297,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 4557,
        review: "Excellent",
        State: "Kuching",
        Email: "-",
        Website: "Website",
        Contact: "+60 - 82588999",
        OperateTime: "Open 24-hours",
        Rating: 5,
        variation: [{ ProductVariationValue: "Long", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 1 }, { ProductVariationValue: "Short", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 2 }, { ProductVariationValue: "Hand", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 3 }],
        Review: [
            {
                Name: "Charles",
                Rating: 5,
                Review: "Nice, very fit my size.",
                Date: "22/04/2022",
            },
            {
                Name: "Stanley",
                Rating: 5,
                Review: "This my 2nd purchase. My kids love it very much",
                Date: "01/05/2022",
            },
            { Name: "Kendy", Rating: 5, Review: "Love this product very much👍🏼", Date: "15/05/2022" },
        ],
        latitude: 1.51317,
        longitude: 110.3357,
        PlaceDesc:
            "Imperial Hotel Kuching, the latest addition to the fast expanding Imperial Group Hotels is a 4-star business class hotel, strategicallt located in the heart of Kuching, just 5 minutes drive from the Kuching International Airport and 10 minutes to the city's central business district. It sits on top of the Boulevard Shoppping Mall and is adjacent to the Imperial Suites",
    },
    {
        image: "https://sarawaktourism.com/TourismApi/images/tourPackage/22.%20Frogging%20(i).jpg",
        name: "Evening Frog Tour",
        shopName: "Matang",
        price: "20",
        discountedPrice: "18",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        locationWise: 8.8,
        Neighborhood: "Kuching",
        reviewNum: 1809,
        review: "Excellent",
    },
    {
        image:
            "https://sarawaktourism.com/v2/wp-content/uploads/2018/10/headhunters-trail-3-600x386.jpg",
        name: "Hike The Headhunter's Trail, Mulu",
        shopName: "Mulu",
        price: "2200",
        discountedPrice: "1800",
        rating: 8.8,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 3577,
        review: "Excellent",
    },
    {
        image: "https://sarawaktourism.com/TourismApi/images/tourPackage/9.%20Jong's%20Crocodile%20(i).jpg",
        name: "Jong’s Crocodile",
        shopName: "Siburan",
        discountedPrice: "10",
        price: "10",
        rating: 7.8,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 2209,
        review: "Very Good",
    },
    {
        image: "https://sarawaktourism.com/v2/wp-content/uploads/2018/09/tanjung-datu-national-park-1-600x399.jpg",
        name: "A Quiet Beach, Turtles and a National Park",
        shopName: "Kuching",
        price: "300",
        discountedPrice: "250",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        locationWise: 8.7,
        Neighborhood: "Kuching",
        reviewNum: 9074,
        review: "Excellent",
    },

    {
        image: "https://sarawaktourism.com/TourismApi/images/tourPackage/4.%20Annah%20Rais%20(i).jpg",
        name: "Annah-Rais Bidayuh Longhouse",
        shopName: "Annah-Rais",
        price: "100",
        discountedPrice: "100",
        rating: 8.2,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 8872,
        review: "Excellent",
    },
];

export const categoriesType = [
    "Exotic",
    "Authentic",
    "Breathtaking",
    "Adventure",
];
export const Division = [
    "Kuching",
    "Sibu",
    "Sri Aman",
    "Miri",
    "Limbang",
    "Sarikei",
    "Kapit",
    "Bintulu",
    "Samarahan",
    "Mukah",
    "Betong",
    "Serian",
];
export const RatingList = [
    { id: 5, value: 5 },
    { id: 4, value: 4 },
    { id: 3, value: 3 },
    { id: 2, value: 2 },
    { id: 1, value: 1 },
];
export const rating = [
    { rate: 5, value: " " },
    { rate: 4, value: " & above" },
    { rate: 3, value: " & above" },
    { rate: 2, value: " & above" },
    { rate: 1, value: " & above" },
    // {rate : 0, value :" - No Ratings"},
]

export const sortingOption = [
    { value: 'latest', label: 'Latest' },
    { value: 'top-sales', label: 'Top Sales' },
    { value: 'low-to-high', label: 'Price Low to High' },
    { value: 'high-to-low', label: 'Price High to Low' }
]

export const swiperImg = [
    { image: "https://s3-ap-southeast-1.amazonaws.com/av-s3/image/large/bcb89fcbc788dfebe44d" },
]