export const recommend = [
    {
        image: "https://sarawaktourism.com/TourismApi/images/gettingthere/electric-bus-600x300.jpg",
        name: "Electric Bus per person",
        shopName: "Sarawak Bus",
        price: "10",
        discountedPrice: "8",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        soldNum: 297,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 4557,
        review: "Excellent",
        State: "Kuching",
        Email: "-",
        Website: "Website",
        Contact: "+60 - 82588999",
        OperateTime: "Open 24-hours",
        Rating: 5,
        variation: [{ ProductVariationValue: "Long", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 1 }, { ProductVariationValue: "Short", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 2 }, { ProductVariationValue: "Hand", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 3 }],
        Review: [
            {
                Name: "Charles",
                Rating: 5,
                Review: "Nice, very fit my size.",
                Date: "22/04/2022",
            },
            {
                Name: "Stanley",
                Rating: 5,
                Review: "This my 2nd purchase. My kids love it very much",
                Date: "01/05/2022",
            },
            { Name: "Kendy", Rating: 5, Review: "Love this product very much👍🏼", Date: "15/05/2022" },
        ],
        latitude: 1.51317,
        longitude: 110.3357,
        PlaceDesc:
            "Imperial Hotel Kuching, the latest addition to the fast expanding Imperial Group Hotels is a 4-star business class hotel, strategicallt located in the heart of Kuching, just 5 minutes drive from the Kuching International Airport and 10 minutes to the city's central business district. It sits on top of the Boulevard Shoppping Mall and is adjacent to the Imperial Suites",
    },
    {
        image: "http://www.insar.com.my/images/gallery/12seater/1.jpg",
        name: "Van - 13 seats",
        shopName: "Car Rental Kuching",
        price: "140",
        discountedPrice: "120",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        locationWise: 8.8,
        Neighborhood: "Kuching",
        reviewNum: 1809,
        review: "Excellent",
    },
    {
        image:
            "https://images.wapcar.my/file1/08660ae50f18495082c8905fccafdef6_606x402.jpg",
        name: "Honda City",
        shopName: "Car Rental Kuching",
        price: "200",
        discountedPrice: "180",
        rating: 8.8,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 3577,
        review: "Excellent",
    },
    {
        image: "https://lh3.googleusercontent.com/TWDcTcZicmtdhOHVakhfz09BNSLYipANM1d57bEoOiO8dCLf-REs3iqKqFN48vf4Y9HUeky2WyJGtG4gSC7M-2PGMlsQ67YTW9qS-T2Pa0c5gPvISGDoqU3RmZK-RRLsSodPwCjwCg=w2400",
        name: "GV 70",
        shopName: "Car Rental Kuching",
        discountedPrice: "250",
        price: "300",
        rating: 7.8,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 2209,
        review: "Very Good",
    },
    {
        image: "https://images.wapcar.my/file1/2a901e5c41854f5dbef723cf75fe1dd7_606x402.jpg",
        name: "Honda Accord",
        shopName: "Car Rental Kuching",
        price: "220",
        discountedPrice: "200",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        locationWise: 8.7,
        Neighborhood: "Kuching",
        reviewNum: 9074,
        review: "Excellent",
    },

    {
        image: "https://images.wapcar.my/file1/b50dfda27ff64ea1b6dd14e2068dd054_606x402.jpg",
        name: "Honda WR-V",
        shopName: "Car Rental Kuching",
        price: "250",
        discountedPrice: "200",
        rating: 8.2,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 8872,
        review: "Excellent",
    },
];

export const categoriesType = [
    "Public",
    "2-5 seats",
    "7 seats",
];
export const Division = [
    "Kuching",
    "Sibu",
    "Sri Aman",
    "Miri",
    "Limbang",
    "Sarikei",
    "Kapit",
    "Bintulu",
    "Samarahan",
    "Mukah",
    "Betong",
    "Serian",
];
export const RatingList = [
    { id: 5, value: 5 },
    { id: 4, value: 4 },
    { id: 3, value: 3 },
    { id: 2, value: 2 },
    { id: 1, value: 1 },
];
export const rating = [
    { rate: 5, value: " " },
    { rate: 4, value: " & above" },
    { rate: 3, value: " & above" },
    { rate: 2, value: " & above" },
    { rate: 1, value: " & above" },
    // {rate : 0, value :" - No Ratings"},
]

export const sortingOption = [
    { value: 'latest', label: 'Latest' },
    { value: 'top-sales', label: 'Top Sales' },
    { value: 'low-to-high', label: 'Price Low to High' },
    { value: 'high-to-low', label: 'Price High to Low' }
]

export const swiperImg = [
    { image: "https://s3-ap-southeast-1.amazonaws.com/av-s3/image/large/bcb89fcbc788dfebe44d" },
]