
import OrangUlu from '../../assets/OrangUlu.jpg'

export const recommend = [
    {
        image:
            "https://s3-ap-southeast-1.amazonaws.com/av-s3/image/large/bcb89fcbc788dfebe44d",
        name: "Wood color Beads",
        shopName: "Shop Anni",
        price: "90",
        discountedPrice: "50",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        soldNum: 297,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 4557,
        review: "Excellent",
        State: "Kuching",
        Email: "-",
        Website: "Website",
        Contact: "+60 - 82588999",
        OperateTime: "Open 24-hours",
        Rating: 5,
        variation: [{ ProductVariationValue: "Long", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 1 },{ ProductVariationValue: "Short", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 2 },{ ProductVariationValue: "Hand", ProductVariationPrice: 20, ProductStockAmount: 12, ProductVariationDetailID: 3 }],
        Review: [
            {
                Name: "Charles",
                Rating: 5,
                Review: "Nice, very fit my size.",
                Date: "22/04/2022",
            },
            {
                Name: "Stanley",
                Rating: 5,
                Review: "This my 2nd purchase. My kids love it very much",
                Date: "01/05/2022",
            },
            { Name: "Kendy", Rating: 5, Review: "Love this product very much👍🏼", Date: "15/05/2022" },
        ],
        latitude: 1.51317,
        longitude: 110.3357,
        PlaceDesc:
            "Imperial Hotel Kuching, the latest addition to the fast expanding Imperial Group Hotels is a 4-star business class hotel, strategicallt located in the heart of Kuching, just 5 minutes drive from the Kuching International Airport and 10 minutes to the city's central business district. It sits on top of the Boulevard Shoppping Mall and is adjacent to the Imperial Suites",
    },
    {
        image: "https://s3-ap-southeast-1.amazonaws.com/av-s3/image/large/2bba8f9c50616dc7cbec",
        name: "Greenish-blue Beads",
        shopName: "Shop Anni",
        price: "10",
        discountedPrice: "5",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        locationWise: 8.8,
        Neighborhood: "Kuching",
        reviewNum: 1809,
        review: "Excellent",
    },
    {
        image: OrangUlu,
        name: "Orang Ulu Multi Purpose Accessory",
        shopName: "Shop Anni",
        price: "120",
        discountedPrice: "100",
        rating: 5,
        Breakfast_Available: true,
        hotelStar: 5,
        locationWise: 8.8,
        Neighborhood: "Kuching",
        reviewNum: 1809,
        review: "Excellent",
    },
    {
        image: "https://ae01.alicdn.com/kf/S6e8520772ef6467fb77dfb1743f919b9c/Lucky-Charm-Tibetan-Buddhism-Bracelets-Bangles-For-Women-Men-Handmade-Knots-Rope-Budda-Thread-Braided-Bracelet.jpg_Q90.jpg_.webp",
        name: "Bracelet (Unisex)",
        shopName: "Shop Anni",
        price: "60",
        discountedPrice: "55",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        locationWise: 8.8,
        Neighborhood: "Kuching",
        reviewNum: 1809,
        review: "Excellent",
    },
    {
        image:
            "https://s3-ap-southeast-1.amazonaws.com/av-s3/image/large/7429e452681cfed78fdd",
        name: "Long Bead necklace",
        shopName: "Shop Anni",
        price: "30",
        discountedPrice: "10",
        rating: 8.8,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 3577,
        review: "Excellent",
    },
    {
        image: "https://s3-ap-southeast-1.amazonaws.com/av-s3/image/large/4d8dee3f5235c1c32157",
        name: "Golden Bead necklace",
        shopName: "Shop Anni",
        discountedPrice: "10",
        price: "30",
        rating: 7.8,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 2209,
        review: "Very Good",
    },
    {
        image: "https://greatleap.com.my/wp-content/uploads/2020/12/bario-rice1.jpg",
        name: "Bario Highland Red Rice",
        shopName: "Beras Sarawak",
        price: "30",
        discountedPrice: "20",
        rating: 8.5,
        Breakfast_Available: true,
        hotelStar: 5,
        locationWise: 8.7,
        Neighborhood: "Kuching",
        reviewNum: 9074,
        review: "Excellent",
    },

    {
        image: "https://sarawakhandicraft.com.my/wp-content/uploads/2020/09/ee7d5cb4-b440-48e2-a834-252f392f05c7.jpg",
        name: "Handwoven penan basket-Small",
        shopName: "Shop Anni",
        price: "45",
        discountedPrice: "35",
        rating: 8.2,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 8872,
        review: "Excellent",
    },
    {
        image: "https://greatleap.com.my/wp-content/uploads/2020/12/WhatsApp-Image-2021-04-22-at-16.06.05.jpeg",
        name: "White Pepper Powder",
        shopName: "Beras Sarawak",
        price: "25",
        discountedPrice: "15",
        rating: 8.2,
        Breakfast_Available: true,
        hotelStar: 4,
        locationWise: 8.5,
        Neighborhood: "Kuching",
        reviewNum: 8872,
        review: "Excellent",
    },
];

export const categoriesType = [
    "Tailormade",
    "Religious",
];
export const Division = [
    "Kuching",
    "Sibu",
    "Sri Aman",
    "Miri",
    "Limbang",
    "Sarikei",
    "Kapit",
    "Bintulu",
    "Samarahan",
    "Mukah",
    "Betong",
    "Serian",
];
export const RatingList = [
    { id: 5, value: 5 },
    { id: 4, value: 4 },
    { id: 3, value: 3 },
    { id: 2, value: 2 },
    { id: 1, value: 1 },
];
export const rating = [
    { rate: 5, value: " " },
    { rate: 4, value: " & above" },
    { rate: 3, value: " & above" },
    { rate: 2, value: " & above" },
    { rate: 1, value: " & above" },
    // {rate : 0, value :" - No Ratings"},
]

export const sortingOption = [
    { value: 'latest', label: 'Latest' },
    { value: 'top-sales', label: 'Top Sales' },
    { value: 'low-to-high', label: 'Price Low to High' },
    { value: 'high-to-low', label: 'Price High to Low' }
]

export const swiperImg = [
    { image: "https://s3-ap-southeast-1.amazonaws.com/av-s3/image/large/bcb89fcbc788dfebe44d" },
]