
import OrangUlu from '../assets/OrangUlu.jpg'

const GeneralData = [
  {
    type: "Accommodation",
    productName: "The Waterfront Hotel Kuching",
    subtitle: "Deluxe Twin",
    ratingStar: 4,
    rating: "4",
    description: "Facilities: Free Wifi, Free Parking, Swimming Pool, Fitness Center, Restaurant, Bar, Spa, 24-hour Front Desk, Room Service, Airport Shuttle, Laundry Service, Business Center, Meeting/Banquet Facilities, Non-smoking Rooms, Facilities for Disabled Guests, Family Rooms, Elevator, Safety Deposit Box, Gift Shop, Car Rental, Air Conditioning, Designated Smoking Area, Airport Shuttle (additional charge),",
    price: 380,
    imgURL: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/214870964.jpg?k=efd2b69118929436a74bc3758e2638c4251d0503d75ff327d5cf40a8f5feeff3&o=",
  },
  {
    type: "Accommodation",
    productName: "The Waterfront Hotel Kuching",
    subtitle: "Standard Suite",
    ratingStar: 4,
    rating: "4",
    description: "Facilities: Free Wifi, Free Parking, Swimming Pool, Fitness Center, Restaurant, Bar, Spa, 24-hour Front Desk, Room Service, Airport Shuttle, Laundry Service, Business Center, Meeting/Banquet Facilities, Non-smoking Rooms, Facilities for Disabled Guests, Family Rooms, Elevator, Safety Deposit Box, Gift Shop, Car Rental, Air Conditioning, Designated Smoking Area, Airport Shuttle (additional charge),",
    price: 280,
    imgURL: "https://cf.bstatic.com/images/hotel/max1024x768/374/37434884.jpg",
  },
  {
    type: "Accommodation",
    productName: "The Waterfront Hotel",
    subtitle: "Deluxe Queen Suite",
    ratingStar: 4,
    rating: "4",
    description: "Facilities: Free Wifi, Free Parking, Swimming Pool, Fitness Center, Restaurant, Bar, Spa, 24-hour Front Desk, Room Service, Airport Shuttle, Laundry Service, Business Center, Meeting/Banquet Facilities, Non-smoking Rooms, Facilities for Disabled Guests, Family Rooms, Elevator, Safety Deposit Box, Gift Shop, Car Rental, Air Conditioning, Designated Smoking Area, Airport Shuttle (additional charge),",
    price: 380,
    imgURL: "https://cf.bstatic.com/images/hotel/max1024x768/374/37425110.jpg",
  },
  {
    type: "Accommodation",
    productName: "Imperial Hotel",
    subtitle: "Superior Twin",
    ratingStar: 4,
    rating: "4",
    description: "Facilities: Free Wifi, Free Parking, Swimming Pool, Fitness Center, Restaurant, Bar, Spa, 24-hour Front Desk, Room Service, Airport Shuttle, Laundry Service, Business Center, Meeting/Banquet Facilities, Non-smoking Rooms, Facilities for Disabled Guests, Family Rooms, Elevator, Safety Deposit Box, Gift Shop, Car Rental, Air Conditioning, Designated Smoking Area, Airport Shuttle (additional charge),",
    price: 300,
    imgURL: "https://q-xx.bstatic.com/xdata/images/hotel/max300/32429247.jpg?k=ed3a961f99232507e7d9c37103961d72c0f40260166a7b056b3b41a5467a2101&o=",
  },
  {
    type: "Accommodation",
    productName: "Imperial Hotel",
    subtitle: " Superior King",
    ratingStar: 4,
    rating: "4",
    description: "Facilities: Free Wifi, Free Parking, Swimming Pool, Fitness Center, Restaurant, Bar, Spa, 24-hour Front Desk, Room Service, Airport Shuttle, Laundry Service, Business Center, Meeting/Banquet Facilities, Non-smoking Rooms, Facilities for Disabled Guests, Family Rooms, Elevator, Safety Deposit Box, Gift Shop, Car Rental, Air Conditioning, Designated Smoking Area, Airport Shuttle (additional charge),",
    price: 300,
    imgURL: "https://q-xx.bstatic.com/xdata/images/hotel/max300/32429248.jpg?k=c92c0e7ec2302493bfe637e7db2ffd90fca57c1f3366c0090a76dbbd1c5e2e46&o=",
  },
  {
    type: "Accommodation",
    productName: "Roxy Hotel",
    subtitle: "Deluxe Double Room",
    ratingStar: 4,
    rating: "4",
    description: "Facilities: Free Wifi, Free Parking, Swimming Pool, Fitness Center, Restaurant, Bar, Spa, 24-hour Front Desk, Room Service, Airport Shuttle, Laundry Service, Business Center, Meeting/Banquet Facilities, Non-smoking Rooms, Facilities for Disabled Guests, Family Rooms, Elevator, Safety Deposit Box, Gift Shop, Car Rental, Air Conditioning, Designated Smoking Area, Airport Shuttle (additional charge),",
    price: 164,
    imgURL: "https://q-xx.bstatic.com/xdata/images/hotel/max300/220233293.jpg?k=ef8dcbe276a47673b21a87d7f6cbbd65679012d875964f94ee44b26794fbfc05&o=",
  },
  //
  {
    type: "Restaurants",
    productName: "King Laksa Restaurant",
    subtitle: "Sarawak Laksa Special",
    ratingStar: 4,
    rating: "4",
    description: "Famous foods: King Laksa Special, King Laksa Ambal, Dabai Fried Rice",
    price: 9,
    imgURL: "https://fastly.4sqi.net/img/general/600x600/24718637_c0dBfmXzBo6TLjZpzT7_t9iGqAqNiirwyaKeP5WSNbU.jpg",
  },
  {
    type: "Restaurants",
    productName: "Haji Salleh",
    subtitle: "Kolok Mee",
    ratingStar: 4,
    rating: "4",
    description: "Famous foods: Mee Kolok",
    price: 4,
    imgURL: "https://cdn-ak.f.st-hatena.com/images/fotolife/m/malaysia_cinta78/20220829/20220829191603.jpg",
  },
  {
    type: "Restaurants",
    productName: "RJ Restaurant",
    subtitle: "Mee Jawa Satay",
    ratingStar: 4,
    rating: "4",
    description: "Famous foods: Mee Jawa Satay, RJ Ayam Penyet",
    price: 9,
    imgURL: "https://lh5.googleusercontent.com/p/AF1QipOMT5ka5v1Kiyu6kKbi9NV-xXT_E2qcv-hHXF-Q=w1080-k-no",
  },
  {
    type: "Restaurants",
    productName: "Mira Kek House",
    subtitle: "Kek Lapis Mira",
    ratingStar: 4,
    rating: "4",
    description: "Famous foods: Kek Lapis Traditional",
    price: 15,
    imgURL: "https://miracakehouse.com/new/wp-content/uploads/2020/08/miracakecentralmatang.jpg",
  },
  {
    type: "Restaurants",
    productName: "Warong Nusantara",
    subtitle: "Peppercorn Beef Rice",
    ratingStar: 4,
    rating: "4",
    description: "Famous foods: Peppercorn Beef Rice",
    price: 10,
    imgURL: "https://media-cdn.tripadvisor.com/media/photo-s/07/e6/e9/4f/warong-nusantara.jpg",
  },
  {
    type: "Restaurants",
    productName: "Ceylonese Kuching",
    subtitle: "Naan Cheese",
    ratingStar: 5,
    rating: "5",
    description: "Famous foods: Banana Leaf Briyani Rice, Naan Cheese, Banana Cheese, Kopi Tarik",
    price: 16,
    imgURL: "https://fastly.4sqi.net/img/general/600x600/62276801_V8OOZxpn6Qlt4ndMffA17KWdE3PIU2ZvWHUqDBinsxY.jpg",
  },
  {
    type: "Tourpackage",
    productName: "Sarawak Sunset River Cruise",
    subtitle: "Bestway Tour & Travel SDN BHD",
    ratingStar: 4,
    rating: "4",
    description: "Experience the signature sunset cruise with your family and loves one. Enjoy a breathtaking 360° panoramic view of Kuching skyline.",
    price: 156,
    imgURL: "https://images.t2u.io/upload/event/listing/0-27132-AWSS387d1b913-b3d9-4394-b422-ab03a9a2a611-Mfmb.jpg",
  },
  {
    type: "Tourpackage",
    productName: "Ukom Longhouse",
    subtitle: "CPH Travel Agencies",
    ratingStar: 5,
    rating: "5",
    description: "Once infamously known as the Land of the Headhunters, a trip to Borneo will be incomplete without a visit to the homes of these once fearsome tribal warriors who remain as heroes in protecting their land which they highly safeguard for ancestral rights.",
    price: 560,
    imgURL: "https://www.startravel.com.my/wp-content/uploads/2023/05/ed4d849e-03ec-4a35-a9fe-397c719f2b50-scaled.jpg",
  },
  {
    type: "Tourpackage",
    productName: "Bako National Park",
    subtitle: "Cat City Holidays SDN BHD",
    ratingStar: 5,
    rating: "5",
    description: "Bako National Park is a national park in Kuching District, Kuching Division, Sarawak, Malaysia. Established in 1957, it is the oldest national park in Sarawak. It covers an area of 27.27 square kilometres at the tip of the Muara Tebas peninsula at the mouth of the Bako and Kuching Rivers.",
    price: 352,
    imgURL: "https://i0.wp.com/borneoadventure.com/v3/wp-content/uploads/2012/01/STB-bako-sea-stack-01.jpg?fit=2000%2C1333&quality=60&strip=all&ssl=1",
  },
  {
    type: "Tourpackage",
    productName: "Gunung Gading Raflessia Tour",
    subtitle: "Cat City Holidays SDN BHD",
    ratingStar: 5,
    rating: "5",
    description: "The Gunung Gading National Park is a national park in Lundu District, Kuching Division, Sarawak, Malaysia. The park is located roughly two hours drive from Kuching, and is a popular destination for seeing the Rafflesia flower in bloom.",
    price: 133,
    imgURL: "https://www.sarawaktourism.com/TourismApi/images/place/426/426_slider1.jpg",
  },
  {
    type: "Tourpackage",
    productName: "Mulu National Park",
    subtitle: "Paradesa Borneo",
    ratingStar: 5,
    rating: "5",
    description: "The Gunung Mulu National Park is a national park in Miri Division, Sarawak, Malaysia. It is a UNESCO World Heritage Site that encompasses caves and karst formations in a mountainous equatorial rainforest settin.",
    price: 159,
    imgURL: "https://blog.qelola.com/wp-content/uploads/2020/06/gunung-mulu-national-park.jpg",
  },
  {
    type: "Ticketing",
    productName: "Brooke Gallery",
    subtitle: "Sarawak Museum",
    ratingStar: 5,
    rating: "5",
    description: "The Brooke Gallery is a museum dedicated to the story of Sarawak's White Rajahs which once ruled Sarawak.",
    price: 15,
    imgURL: "https://56hotel.com.my/wp-content/uploads/2017/08/Fort-Margherita.jpg",
  },
  {
    type: "Ticketing",
    productName: "Textile Museum",
    subtitle: "SarawakTour SDN BHD",
    ratingStar: 5,
    rating: "5",
    description: "The museum displays the textiles made by local communities in Sarawak, as well as traditional costumes and accessories. It also showcases the stages of textile manufacturing processes.",
    price: "FOC",
    imgURL: "https://live.staticflickr.com/8456/7903406596_b90ba0b346_b.jpg",
  },
  {
    type: "Ticketing",
    productName: "Adult (3 days Pass)",
    subtitle: "Sarawak Cultural Village",
    ratingStar: 5,
    rating: "5",
    description: "The Rainforest World Music Festival (often abbreviated as RWMF) is an annual three-day music festival celebrating the diversity of world music, held in Kuching, Sarawak, Malaysia, with daytime music workshops, cultural displays, craft displays, food stalls, and main-stage evening concerts.",
    price: 345,
    imgURL: "https://rwmf.net/wp-content/uploads/2023/04/RWMF-WEB-BANNER-1-1.jpg",
  },
  {
    type: "Ticketing",
    productName: "Adult (1 days Pass)",
    subtitle: "Sarawak Cultural Village",
    ratingStar: 5,
    rating: "5",
    description: "The Rainforest World Music Festival (often abbreviated as RWMF) is an annual three-day music festival celebrating the diversity of world music, held in Kuching, Sarawak, Malaysia, with daytime music workshops, cultural displays, craft displays, food stalls, and main-stage evening concerts.",
    price: 140,
    imgURL: "https://rwmf.net/wp-content/uploads/2023/04/RWMF-WEB-BANNER-1-1.jpg",
  },
  {
    type: "Ticketing",
    productName: "Family (3 days Pass)",
    subtitle: "Sarawak Cultural Village",
    ratingStar: 5,
    rating: "5",
    description: "The Rainforest World Music Festival (often abbreviated as RWMF) is an annual three-day music festival celebrating the diversity of world music, held in Kuching, Sarawak, Malaysia, with daytime music workshops, cultural displays, craft displays, food stalls, and main-stage evening concerts.",
    price: 1020,
    imgURL: "https://rwmf.net/wp-content/uploads/2023/04/RWMF-WEB-BANNER-1-1.jpg",
  },
  {
    type: "Product",
    productName: "Orang Ulu Multi Purpose Accessory",
    subtitle: "LL Handcraft (aka Glass Coaster)",
    ratingStar: 5,
    rating: "5",
    description: "",
    price: 120,
    imgURL: OrangUlu,
  },
  {
    type: "Product",
    productName: "Tango Budak",
    subtitle: "LNB Handcraft",
    ratingStar: 5,
    rating: "5",
    description: "",
    price: 399,
    imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKNlZchapOzvSDaSvYUAB2VHJ6q7rg6Ww9OkqnmRfkPwtBy5cJWL3Z7YZM6w-i6yT55nQ&usqp=CAU",
  },
  {
    type: "Product",
    productName: "Ceramic Necklace (Mint)",
    subtitle: "Mka Craft",
    ratingStar: 5,
    rating: "5",
    description: "",
    price: 99,
    imgURL: "https://sarawakhandicraft.com.my/wp-content/uploads/2019/10/IMG_20191026_0922421.jpg",
  },
  {
    type: "Product",
    productName: "Bracelet (Unisex)",
    subtitle: "Julia Jayne",
    ratingStar: 5,
    rating: "5",
    description: "",
    price: 60,
    imgURL: "https://ae01.alicdn.com/kf/S6e8520772ef6467fb77dfb1743f919b9c/Lucky-Charm-Tibetan-Buddhism-Bracelets-Bangles-For-Women-Men-Handmade-Knots-Rope-Budda-Thread-Braided-Bracelet.jpg_Q90.jpg_.webp",
  },
  {
    type: "Product",
    productName: "Bidayuh Traditional (Fullset of 7)",
    subtitle: "Paradesa Borneo",
    ratingStar: 5,
    rating: "5",
    description: "",
    price: 539,
    imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh6BSbFX8zfQWetwikZP6mf0tbPrXW1oILqRm8vFODwigu66zUGwKjSAYbae5F0lzLXGk&usqp=CAU",
  },
  //
  {
    type: "Transportation",
    imgURL: "http://www.insar.com.my/images/gallery/12seater/1.jpg",
    productName: "Van - 13 seats",
    subtitle: "Car Rental Kuching",
    price: 140,
    rating: "5",
    ratingStar: 5,
    description: "13 seats",
  },
  {
    type: "Transportation",
    imgURL:
      "https://images.wapcar.my/file1/08660ae50f18495082c8905fccafdef6_606x402.jpg",
    productName: "Honda City",
    subtitle: "Car Rental Kuching",
    price: 200,
    rating: "5",
    ratingStar: 5,
    description: "5 seats",
  },
  {
    type: "Transportation",
    imgURL: "https://lh3.googleusercontent.com/TWDcTcZicmtdhOHVakhfz09BNSLYipANM1d57bEoOiO8dCLf-REs3iqKqFN48vf4Y9HUeky2WyJGtG4gSC7M-2PGMlsQ67YTW9qS-T2Pa0c5gPvISGDoqU3RmZK-RRLsSodPwCjwCg=w2400",
    productName: "GV 70",
    subtitle: "Car Rental Kuching",
    price: 300,
    rating: "5",
    ratingStar: 5,
    description: "5 seats",
  },
  {
    type: "Transportation",
    imgURL: "https://images.wapcar.my/file1/2a901e5c41854f5dbef723cf75fe1dd7_606x402.jpg",
    productName: "Honda Accord",
    subtitle: "Car Rental Kuching",
    price: 220,
    rating: "5",
    ratingStar: 5,
    description: "5 seats",
  },

  {
    type: "Transportation",
    imgURL: "https://images.wapcar.my/file1/b50dfda27ff64ea1b6dd14e2068dd054_606x402.jpg",
    productName: "Honda WR-V",
    subtitle: "Car Rental Kuching",
    price: 250,
    rating: "5",
    ratingStar: 5,
    description: "5 seats",
  },
]

export default GeneralData;