export const tourGuides = [
  {
    id: 1,
    name: "Stephanie",
    image: "https://www.amazingborneo.com/img/stephanie.jpg",
    rating: 5,
    review: 53,
    price: 80,
  },
  {
    id: 2,
    name: "Calvin",
    image: "https://www.amazingborneo.com/img/Calvin.jpg",
    rating: 5,
    review: 32,
    price: 100,
  },
  {
    id: 3,
    name: "Tan",
    image: "https://www.amazingborneo.com/img/tan.jpg",
    rating: 4.9,
    review: 41,
    price: 90,
  },
  {
    id: 4,
    name: "Luq",
    image: "https://www.amazingborneo.com/img/luq.jpg",
    rating: 4.8,
    review: 37,
    price: 75,
  },
  {
    id: 5,
    name: "Azmil",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH490cP9eH_X8F6ofao23DBIa9Z0uoCELDcTpCNCMGaA0XfX_rF-HJKdke5cRazbe6pbA&usqp=CAU",
    rating: 5,
    review: 36,
    price: 80,
  },
  {
    id: 6,
    name: "Roy",
    image: "https://www.amazingborneo.com/img/roy.jpg",
    rating: 4.9,
    review: 47,
    price: 85,
  },
]